
spring:
  datasource:
    url: jdbc:mysql://123.56.98.228:3306/toolmaker
    username: root
    password: YUNFEI
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 123.56.98.228
    password: YUNFEI
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 10MB


mybatis-plus:
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  auto-dialect: on  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式
  reasonable: true #分页合理化参数，默认值为 false 。当该参数设置为 true 时， pageNum<=0 时会查询第一页， pageNum>pages （超过总数时），会查询最后一页
  support-methods-arguments: true #支持通过Mapper接口参数传递page参数,默认值为false
  page-size-zero: true #默认值为 false ，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit =0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）

weather-info:
  app-key: 36153ab95ab0be1070258f5a55725ae9

email-sender:
  senderEmail: 1361573692@qq.com
  password: fqpobvgkwuotffjj

codegen:
  mybatis-mapper:
    templateName: template.ftlh

logging:
  level:
    root: debug
  config: classpath:logback.xml

knife4j:
  enable: true
  documents:
    - group: Test Group
      name: My Documents
      locations: classpath:wiki/*
  setting:
    # default lang
    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT | [Tool Maker]()
    # header
    enableHomeCustom: true
    homeCustomLocation: classpath:wiki/README.md
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models

#rocketmq:
#  name-server: 123.56.98.228:9876
#  producer:
#    group: platform-sms-server-group
#    sendMessageTimeout: 10000
#  consumer1:
#    group: platform-sms-worker-common-group
#    topic: sms-common-topic
