
spring:
  datasource:
    url: jdbc:mysql://43.143.229.22:3306/toolmaker
    username: root
    password: yunfei
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 43.143.229.22
    password: yunfei
  session:
    store-type: redis

mybatis-plus:
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

weather-info:
  app-key: 36153ab95ab0be1070258f5a55725ae9

email-sender:
  senderEmail: 1361573692@qq.com
  password: fqpobvgkwuotffjj

logging:
  level:
    root: debug
  config: classpath:logback.xml
